/**
 * @file crzt02.c
 * @brief CRZT02 returns || I - Q'*Q || / (M * eps) for CTZRZF.
 *
 * Port of LAPACK TESTING/LIN/crzt02.f to C.
 */

#include <math.h>
#include "verify.h"

/**
 * CRZT02 returns
 *    || I - Q'*Q || / (M * eps)
 * where the matrix Q is defined by the Householder transformations
 * generated by CTZRZF.
 *
 * @param[in]  m     The number of rows of the matrix AF.
 * @param[in]  n     The number of columns of the matrix AF.
 * @param[in]  AF    Array (lda, n). The output of CTZRZF.
 * @param[in]  lda   The leading dimension of the array AF.
 * @param[in]  tau   Array (m). Details of the Householder transformations.
 * @param[out] work  Array (lwork). Workspace.
 * @param[in]  lwork The length of the array work. lwork >= n*n + n.
 *
 * @return || I - Q'*Q || / (M * eps).
 */
f32 crzt02(const INT m, const INT n, c64* AF, const INT lda,
              const c64* tau, c64* work, const INT lwork)
{
    const c64 CZERO = CMPLXF(0.0f, 0.0f);
    const c64 CONE = CMPLXF(1.0f, 0.0f);
    const f32 ZERO = 0.0f;
    const f32 ONE = 1.0f;
    INT i, info;
    f32 rwork[1];

    /* Quick return if possible */
    if (m <= 0 || n <= 0) {
        return ZERO;
    }

    /* Test for sufficient workspace */
    if (lwork < n * n + n) {
        return ZERO;
    }

    /* Q := I */
    claset("F", n, n, CZERO, CONE, work, n);

    /* Q := P(0) * ... * P(m-1) * Q */
    cunmrz("L", "N", n, n, m, n - m, AF, lda, tau,
           work, n, &work[n * n], lwork - n * n, &info);

    /* Q := P(m-1)' * ... * P(0)' * Q = Q' * Q */
    cunmrz("L", "C", n, n, m, n - m, AF, lda, tau,
           work, n, &work[n * n], lwork - n * n, &info);

    /* Q := Q - I */
    for (i = 0; i < n; i++) {
        work[i * n + i] -= ONE;
    }

    /* Compute ||Q - I|| / (eps * max(M,N)) */
    return clange("1", n, n, work, n, rwork) /
           (slamch("E") * (f32)((m > n) ? m : n));
}
