/**
 * @file zrzt02.c
 * @brief ZRZT02 returns || I - Q'*Q || / (M * eps) for ZTZRZF.
 *
 * Port of LAPACK TESTING/LIN/zrzt02.f to C.
 */

#include <math.h>
#include "verify.h"

/**
 * ZRZT02 returns
 *    || I - Q'*Q || / (M * eps)
 * where the matrix Q is defined by the Householder transformations
 * generated by ZTZRZF.
 *
 * @param[in]  m     The number of rows of the matrix AF.
 * @param[in]  n     The number of columns of the matrix AF.
 * @param[in]  AF    Array (lda, n). The output of ZTZRZF.
 * @param[in]  lda   The leading dimension of the array AF.
 * @param[in]  tau   Array (m). Details of the Householder transformations.
 * @param[out] work  Array (lwork). Workspace.
 * @param[in]  lwork The length of the array work. lwork >= n*n + n.
 *
 * @return || I - Q'*Q || / (M * eps).
 */
f64 zrzt02(const INT m, const INT n, c128* AF, const INT lda,
              const c128* tau, c128* work, const INT lwork)
{
    const c128 CZERO = CMPLX(0.0, 0.0);
    const c128 CONE = CMPLX(1.0, 0.0);
    const f64 ZERO = 0.0;
    const f64 ONE = 1.0;
    INT i, info;
    f64 rwork[1];

    /* Quick return if possible */
    if (m <= 0 || n <= 0) {
        return ZERO;
    }

    /* Test for sufficient workspace */
    if (lwork < n * n + n) {
        return ZERO;
    }

    /* Q := I */
    zlaset("F", n, n, CZERO, CONE, work, n);

    /* Q := P(0) * ... * P(m-1) * Q */
    zunmrz("L", "N", n, n, m, n - m, AF, lda, tau,
           work, n, &work[n * n], lwork - n * n, &info);

    /* Q := P(m-1)' * ... * P(0)' * Q = Q' * Q */
    zunmrz("L", "C", n, n, m, n - m, AF, lda, tau,
           work, n, &work[n * n], lwork - n * n, &info);

    /* Q := Q - I */
    for (i = 0; i < n; i++) {
        work[i * n + i] -= ONE;
    }

    /* Compute ||Q - I|| / (eps * max(M,N)) */
    return zlange("1", n, n, work, n, rwork) /
           (dlamch("E") * (f64)((m > n) ? m : n));
}
