#!/usr/bin/env python3
"""Generate lapack_name_map.h from public header declarations.

Reads all SEMICOLON_API function declarations from the precision and auxiliary
headers, and produces a renaming header that maps each function name through
the LAPACK_NAME() macro. This header is only active when SEMICOLON_ILP64 is
defined.

Usage:
    python tools/generate_name_map.py
"""

import re
import os

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(SCRIPT_DIR)
INCLUDE_DIR = os.path.join(PROJECT_ROOT, "src", "include")

HEADERS = [
    "semicolon_lapack_double.h",
    "semicolon_lapack_single.h",
    "semicolon_lapack_complex_double.h",
    "semicolon_lapack_complex_single.h",
    "semicolon_lapack_auxiliary.h",
]

OUTPUT = os.path.join(INCLUDE_DIR, "lapack_name_map.h")

# Matches: SEMICOLON_API <return_type> <function_name>(
DECL_RE = re.compile(r"SEMICOLON_API\s+\w+\s+(\w+)\s*\(")


def extract_functions(header_path):
    """Extract function names from a header file."""
    names = []
    with open(header_path) as f:
        for line in f:
            m = DECL_RE.search(line)
            if m:
                names.append(m.group(1))
    return names


def main():
    all_names = []
    per_header = {}

    for header in HEADERS:
        path = os.path.join(INCLUDE_DIR, header)
        names = extract_functions(path)
        per_header[header] = len(names)
        all_names.extend(names)

    # Check for duplicates
    seen = {}
    duplicates = []
    for name in all_names:
        if name in seen:
            duplicates.append((name, seen[name]))
        else:
            seen[name] = name

    unique_names = sorted(seen.keys())

    # Write the output header
    with open(OUTPUT, "w") as f:
        f.write(
            "/* Auto-generated by tools/generate_name_map.py — do not edit.\n"
            "   Regenerate with: python tools/generate_name_map.py */\n"
            "#ifndef SEMICOLON_LAPACK_NAME_MAP_H\n"
            "#define SEMICOLON_LAPACK_NAME_MAP_H\n"
            "\n"
        )
        for name in unique_names:
            f.write(f"#define {name} LAPACK_NAME({name})\n")
        f.write(
            "\n"
            "#endif /* SEMICOLON_LAPACK_NAME_MAP_H */\n"
        )

    # Summary
    print(f"Generated {OUTPUT}")
    print(f"Total unique functions: {len(unique_names)}")
    for header, count in per_header.items():
        print(f"  {header}: {count}")
    if duplicates:
        print(f"Duplicates found (across headers, deduplicated): {len(duplicates)}")
    else:
        print("No duplicates found.")


if __name__ == "__main__":
    main()
