/* AUTO-GENERATED FILE — DO NOT EDIT
 * Fortran-ABI compatibility shim for semicolon-lapack
 * Precision: auxiliary
 * Source header: semicolon_lapack_auxiliary.h
 * Generated by scripts/generate_fortran_shim.py
 */

#include <stdlib.h>
#include "semicolon_lapack_auxiliary.h"


void xerbla_(char* srname, INT* info) {
    xerbla(srname, *info);
}

INT ieeeck_(INT* ispec, float* zero, float* one) {
    INT _ret = ieeeck(*ispec, *zero, *one);
    return _ret;
}

INT ilaenv2stage_(INT* ispec, char* name, char* opts, INT* n1, INT* n2, INT* n3, INT* n4) {
    INT _ret = ilaenv2stage(*ispec, name, opts, *n1, *n2, *n3, *n4);
    return _ret;
}

INT iparam2stage_(INT* ispec, char* name, char* opts, INT* ni, INT* nbi, INT* ibi, INT* nxi) {
    INT _ret = iparam2stage(*ispec, name, opts, *ni, *nbi, *ibi, *nxi);
    return _ret;
}

INT iparmq_(INT* ispec, char* name, char* opts, INT* n, INT* ilo, INT* ihi, INT* lwork) {
    INT _ret = iparmq(*ispec, name, opts, *n, *ilo, *ihi, *lwork);
    return _ret;
}
